### ISSUE TITLE
getCommentType limits parsing to *only* CSS or HTML

### ISSUE THREAD

**Issue by mirisuzanne** [himedlooff/doxray#25]
Hi @himedlooff - based on my success making this work with 11ty for css documentation, I decided to try and port my solution to document nunjucks macros:

```js
const doxOptions = {
  regex: {
    njk: {
      opening: /^\{\#*\s*@docs[^\n]*\n/m,
      closing: /\#\}/,
      comment: /^\{\#\s*@docs[^*]*\#+(?:[^/*][^*]*\#+)*\}/gm,
      ignore: /^\{\#\s*@no-docs[\s\S]*/gm
    }
  }
};

fs.readdir(includeDir, (err, files) => {
  if (err) throw err;
  files.filter((file) => file.endsWith('.njk')).forEach((file) => {
    const docs = doxray([filePath], doxOptions);
  }
}
```
This returns an error:

```
Uncaught exception: (more in DEBUG output)
> Cannot read property 'comment' of undefined

`TypeError` was thrown:
    TypeError: Cannot read property 'comment' of undefined
        at Object.utils.getFileContents (/Users/miriamsuzanne/Sites/oddleventy/node_modules/doxray/utils.js:99:41)
        at Doxray.<anonymous> (/Users/miriamsuzanne/Sites/oddleventy/node_modules/doxray/doxray.js:68:42)
        at Array.forEach (<anonymous>)
        at Doxray.parse (/Users/miriamsuzanne/Sites/oddleventy/node_modules/doxray/doxray.js:64:7)
        at Doxray.run (/Users/miriamsuzanne/Sites/oddleventy/node_modules/doxray/doxray.js:49:17)
        at doxray (/Users/miriamsuzanne/Sites/oddleventy/node_modules/doxray/index.js:10:25)
        at files.filter.forEach (/Users/miriamsuzanne/Sites/oddleventy/content/_data/dox.js:35:20)
        at Array.forEach (<anonymous>)
        at fs.readdir (/Users/miriamsuzanne/Sites/oddleventy/content/_data/dox.js:31:51)
        at FSReqWrap.args [as oncomplete] (fs.js:140:20)
```

After some testing, it looks like the problem is in the `getCommentType()` switch, which forces any unknown extension into `css`. In fact, it works if I register my new regex patterns as `css` in the options object, and continue to run it on `.njk` files.

**Comment by himedlooff** [comment]
Thanks for reporting that. Seems like a bad design choice on my end 😰
I can set aside some time tomorrow to look into it.

**Comment by mirisuzanne** [comment]
I can see why it's there, tho: real quick solution for handling various css preprocessor file types. Should be simple enough to move that defaulting step to the point at which the regex is needed, rather than the point where the extension is captured - so it only defaults to CSS if the existing extension has no regex defined. 

I think it would also help merge custom regex definitions with the built-in ones. Not only was it treating my `.njk` files as `css`, but it was allowing my regex map to completely remove the default `css` regex settings - returning `undefined` for `options.regex[ ext ]`. Does that warrant a new issue, or can it fall under the same general problem?

I can attempt an initial PR if that's helpful? Thanks!

**Comment by himedlooff** [comment]
Yes feel free to try out a solution. I'd love to see it.
