### ISSUE TITLE
Breaks with js-yaml >= 4.

### ISSUE THREAD

**Issue by jgerigmeyer** [himedlooff/doxray#29]
Dependency `js-yaml@4` has breaking changes (https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md), but is pinned only as `>=3.13.1` (https://github.com/himedlooff/doxray/blob/master/package.json#L32). This results in an error trying to use the now-removed `yaml.safeLoad` fn (https://github.com/himedlooff/doxray/blob/master/utils.js#L120) when `js-yaml@4` is used.

```
> Error converting comment #1 to YAML. Please check for formatting errors.

`Error` was thrown:
    Error: Error converting comment #1 to YAML. Please check for formatting errors.
        at Object.utils.convertYaml (.../.yarn/cache/doxray-npm-0.10.0-a541a1e2bf-4a7d43c6be.zip/node_modules/doxray/utils.js:128:11)
        at Object.<anonymous> (.../.yarn/cache/doxray-npm-0.10.0-a541a1e2bf-4a7d43c6be.zip/node_modules/doxray/utils.js:63:26)
        at Array.forEach (<anonymous>)
        at Object.utils.parseOutDocs (.../.yarn/cache/doxray-npm-0.10.0-a541a1e2bf-4a7d43c6be.zip/node_modules/doxray/utils.js:59:8)
        at Doxray.<anonymous> (.../.yarn/cache/doxray-npm-0.10.0-a541a1e2bf-4a7d43c6be.zip/node_modules/doxray/doxray.js:71:34)
        at Array.forEach (<anonymous>)
        at Doxray.parse (.../.yarn/cache/doxray-npm-0.10.0-a541a1e2bf-4a7d43c6be.zip/node_modules/doxray/doxray.js:64:7)
        at Doxray.run (.../.yarn/cache/doxray-npm-0.10.0-a541a1e2bf-4a7d43c6be.zip/node_modules/doxray/doxray.js:49:17)
        at doxray (.../.yarn/cache/doxray-npm-0.10.0-a541a1e2bf-4a7d43c6be.zip/node_modules/doxray/index.js:10:25)
```

**Comment by himedlooff** [comment]
Thanks for reporting! I'll pin to 3.13.1 for now.

**Comment by himedlooff** [comment]
Published https://www.npmjs.com/package/doxray
Will look into supporting js-yaml 4 a little later but this should stop your breaking builds for now.
